name: Build

on:
  - push
  - pull_request
  - workflow_call

jobs:
  install-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/build